package ru.sicampus.bootcamp2026.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    ACCESS_DENIED,
    NOT_FOUND,
    INTERNAL_ERROR,

    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,

    MEETING_NOT_FOUND,
    MEETING_TIME_CONFLICT,
    MEETING_ACCESS_DENIED,

    INVITATION_NOT_FOUND,
    INVITATION_ALREADY_EXISTS,
    INVITATION_ALREADY_RESPONDED,
    INVITATION_ACCESS_DENIED
}
