spring.application.name=bootcamp2026

# Database Configuration
spring.datasource.url=jdbc:h2:mem:bootcamp2026
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
