spring:
  mail:
    host: ${smtp_server}
    port: ${port}
    username: ${S_EMAIL}
    password: ${S_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:file:./data/bootcampdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true

    change-log: db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true