spring.application.name=bunch

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/bunch_db
spring.datasource.username=bunch
spring.datasource.password=0001
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# LIQUIBASE
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=public

# LOGGING
logging.level.liquibase=debug
logging.level.org.springframework=info