spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/application_db
    username: applicationuser
    password: gkl370WVUPMgLhK
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  forward-headers-strategy: framework