server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    liquibase: info

jwt:
  secret: "dev-secret-for-industrial-backend-2026-please-change-in-prod"
  access-token:
    expiration-ms: 604800000   # 7 days
  refresh-token:
    expiration-ms: 2592000000  # 30 days