spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meeting_planner
    username: postgres
    password: MasRom101
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
    show-sql: false
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    ru.examle.edu: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE